# Generated by Django 3.2.25 on 2024-06-20 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
